name: Update README

on:
  push:
    branches: [master]
  workflow_disaptch: {}

jobs:
  reorganize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate table with `lpm`
        run: |
          wget https://github.com/lite-xl/lite-xl-plugin-manager/releases/download/latest/lpm.x86_64-linux -O lpm
          chmod +x lpm
          ./lpm table manifest.json README.md
          if ! git diff --exit-code -s README.md; then
            git config --global user.name "Github Actions" && git config --global user.email "<>"
            git add README.md 
            git commit -m '[CI] Updated README.md.'
            git push
          fi
